export const mockShow = {
  name: 'Test Show',
  image: {
    medium: 'https://example.com/image.jpg',
    original: 'https://example.com/image_original.jpg',
  },
  rating: {
    average: 8.5,
  },
  language: 'English',
  network: {
    id: 3,
    name: 'ABC',
    country: {
      name: 'United States',
      code: 'US',
      timezone: 'America/New_York',
    },
    officialSite: 'https://abc.com/',
  },
  id: 31,
  url: 'https://www.tvmaze.com/shows/31/marvels-agents-of-shield',
  type: 'Scripted',
  genres: ['Action', 'Adventure', 'Science-Fiction'],
  status: 'Ended',
  runtime: 60,
  averageRuntime: 60,
  premiered: '2013-09-24',
  ended: '2020-08-12',
  officialSite: 'http://abc.go.com/shows/marvels-agents-of-shield',
  schedule: {time: '22:00', days: ['Wednesday']},
  weight: 99,
  webChannel: null,
  dvdCountry: null,
  externals: {tvrage: 32656, thetvdb: 263365, imdb: 'tt2364582'},
  summary: '',
  updated: 1732364470,
  _links: {
    self: {href: 'https://api.tvmaze.com/shows/31'},
    previousepisode: {
      href: 'https://api.tvmaze.com/episodes/1839340',
      name: '',
    },
  },
};
